# forwarding_chat: -1002023134958
forwarding_chat: 766828537
admins_ids: 
  - 520248084 # Вадим
  - 766828537 # Никита
subscription_price: 399
bot_link: https://t.me/unicode_dev_bot
general_chats:
  "UNI: ОСНОВНОЙ": "https://t.me/+Pphu6iu6VGwwYmRi"
additional_chats:
  "UNI: резюме": "https://t.me/+vLW1bN_CDE5iZWM6"
  "UNI: python": "https://t.me/+3iec-KVDof4wZGIy"
  "UNI: data science": "https://t.me/+-yVI9LU9klk2ZjJi"
  "UNI: база знаний": "https://t.me/+UWs3Kbqu6uUzNWZi"
folder_with_chats: https://t.me/addlist/l69T0iycJCMwMTZi
unicode_chat_ids:
  - -1001940645326 # UNI: ФЛУДИЛКА
  - -1002127591137 # UNI: база знаний
  - -1002113918762 # UNI: data science
  - -1001790347884 # UNI: резюме
  - -1002000617428 # UNI: python
