version: '3.7'
services:
  db:
    container_name: "postgres"
    image: postgres:14-alpine
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_NAME}
      - POSTGRES_HOST=${POSTGRES_HOST}
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: on-failure
    ports:
      - "5432:5432"
  bot:
    container_name: "bot"
    build: .
    command: python3 bot.py
    env_file:
      - ./.env
    restart: always
    depends_on:
      - db
  webhook:
    container_name: "bot_webhook"
    build: .
    command: python3 -m uvicorn --host 0.0.0.0 --port 8000 webhook:app
    env_file:
      - ./.env
    restart: always
    depends_on:
      - db
    ports:
      - "8000:8000"
volumes:
  pgdata: